Refactoring
Simplon-devs/maldives-corals pull request #1
Opened 2023-04-24 15:22 UTC by brmuloot

Avancement sur la partie de refactoring les structures qui ont un masks sont toutes redimensionner et prête à l'usage

2023-04-25 15:24 UTC, ValBaron10 requested changes
Take off all the images, they must not be uploaded in the Github repo.
Once they have been removed, do the pull request again.

2023-04-26 07:29 UTC, brmuloot commented
I take off all images and the json file

2023-04-26 07:31 UTC, LakhbirSin approved these changes

2023-04-26 07:57 UTC, ValBaron10 approved these changes
@brmuloot @LakhbirSin @Mehdi-212 @Sophana63 Be careful, these changes will certainly create merge conflicts as you are working on the same files and in the same folders, renaming them differently.
If these merge conflicts occur, take a look together where and which they are to resolve them and continue to work with the same conventions.

2023-04-26 07:57 UTC, merged